=== ldlaur/ares/docs/theme/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Custom theme for ARES",
  "type": "object",
  "properties": {
    "base0": {
      "type": "string",
      "minLength": 1
    },
    "base1a": {
      "type": "string",
      "minLength": 1
    },
    "base1": {
      "type": "string",
      "minLength": 1
    },
    "base2": {
      "type": "string",
      "minLength": 1
    },
    "base3": {
      "type": "string",
      "minLength": 1
    },
    "base4": {
      "type": "string",
      "minLength": 1
    },
    "text": {
      "type": "string",
      "minLength": 1
    },
    "testsuite-red": {
      "type": "string",
      "minLength": 1
    },
    "testsuite-green": {
      "type": "string",
      "minLength": 1
    },
    "editor-selection-match": {
      "type": "string",
      "minLength": 1
    },
    "editor-activeline": {
      "type": "string",
      "minLength": 1
    },
    "button-hover": {
      "type": "string",
      "minLength": 1
    },
    "button-active": {
      "type": "string",
      "minLength": 1
    },
    "sp-highlight": {
      "type": "string",
      "minLength": 1
    },
    "fp-highlight": {
      "type": "string",
      "minLength": 1
    },
    "border": {
      "type": "string",
      "minLength": 1
    },
    "regtable-special": {
      "type": "string",
      "minLength": 1
    },
    "regtable-temp": {
      "type": "string",
      "minLength": 1
    },
    "regtable-arg": {
      "type": "string",
      "minLength": 1
    },
    "regtable-saved": {
      "type": "string",
      "minLength": 1
    },
    "pseudoinst": {
      "type": "string",
      "minLength": 1
    },
    "inst": {
      "type": "string",
      "minLength": 1
    },
    "addrcolumn": {
      "type": "string",
      "minLength": 1
    },
    "debugging": {
      "type": "string",
      "minLength": 1
    },
    "editor-caret": {
      "type": "string",
      "minLength": 1
    },
    "editor-insn": {
      "type": "string",
      "minLength": 1
    },
    "editor-reg": {
      "type": "string",
      "minLength": 1
    },
    "editor-const": {
      "type": "string",
      "minLength": 1
    },
    "editor-string": {
      "type": "string",
      "minLength": 1
    },
    "editor-directive": {
      "type": "string",
      "minLength": 1
    },
    "editor-comment": {
      "type": "string",
      "minLength": 1
    }
  },
  "required": [
    "base0",
    "base1a",
    "base1",
    "base2",
    "base3",
    "base4",
    "text",
    "testsuite-red",
    "testsuite-green",
    "editor-selection-match",
    "editor-activeline",
    "button-hover",
    "button-active",
    "sp-highlight",
    "fp-highlight",
    "border",
    "regtable-special",
    "regtable-temp",
    "regtable-arg",
    "regtable-saved",
    "pseudoinst",
    "inst",
    "addrcolumn",
    "debugging",
    "editor-caret",
    "editor-insn",
    "editor-reg",
    "editor-const",
    "editor-string",
    "editor-directive",
    "editor-comment"
  ]
}

=== ldlaur/ares/docs/theme/template.json
{
  "base0": "",
  "base1a": "",
  "base1": "",
  "base2": "",
  "base3": "",
  "base4": "",
  "text": "",
  "testsuite-red": "",
  "testsuite-green": "",
  "editor-selection-match": "",
  "editor-activeline": "",
  "button-hover": "",
  "button-active": "",
  "sp-highlight": "",
  "fp-highlight": "",
  "border": "",
  "regtable-special": "",
  "regtable-temp": "",
  "regtable-arg": "",
  "regtable-saved": "",
  "pseudoinst": "",
  "inst": "",
  "addrcolumn": "",
  "debugging": "",
  "editor-caret": "",
  "editor-insn": "",
  "editor-reg": "",
  "editor-const": "",
  "editor-string": "",
  "editor-directive": "",
  "editor-comment": ""
}
